from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the crywolf index.<br><br>Looking to <a href='/fail'>fail</a>?")

def fail(request):
    raise RuntimeError, "This is a runtime error generated by the crywolf app."
